import { FormEvent, useCallback, useEffect, useState } from 'react';
import { createRoot } from 'react-dom/client';
import './styles.css';

const API = import.meta.env.VITE_API_BASE_URL ?? 'http://localhost:3000';
const ADMIN_KEY = import.meta.env.VITE_ADMIN_KEY ?? 'buscasp-local-admin';
type Page = 'dashboard'|'products'|'wanted'|'users'|'reports'|'categories'|'regions';
type Row = Record<string, any>;

const labels: Record<Page,string> = {dashboard:'运营概览',products:'商品管理',wanted:'找货需求',users:'用户管理',reports:'举报中心',categories:'分类配置',regions:'地区管理'};
const statusText: Record<string,string> = {PUBLISHED:'展示中',OFF_SHELF:'已下架',SOLD:'已售出',VIOLATION:'违规下架',ACTIVE:'正常',LIMITED:'受限',BANNED:'封禁',FOUND:'已找到',EXPIRED:'已过期',OPEN:'待处理',PROCESSING:'处理中',CLOSED:'已关闭',DISABLED:'已停用'};

async function api(path:string, init:RequestInit={}) {
  const response=await fetch(`${API}${path}`,{...init,headers:{...(init.body?{'content-type':'application/json'}:{}),'x-admin-key':ADMIN_KEY,...init.headers}});
  const data=await response.json().catch(()=>({}));
  if(!response.ok) throw new Error(data.message || '操作失败');
  return data;
}
const fmt=(date:string)=>date?new Date(date).toLocaleString('zh-CN'):'—';
const badge=(status:string)=><span className={`badge ${status?.toLowerCase()}`}>{statusText[status]??status}</span>;

function Modal({title,onClose,children}:{title:string;onClose:()=>void;children:React.ReactNode}){
  return <div className="modal-backdrop" onMouseDown={e=>e.target===e.currentTarget&&onClose()}><div className="modal"><div className="modal-head"><h2>{title}</h2><button className="icon" onClick={onClose}>×</button></div>{children}</div></div>;
}

function ProductForm({row,users,categories,onClose,onSaved}:{row?:Row;users:Row[];categories:Row[];onClose:()=>void;onSaved:()=>void}){
  const [form,setForm]=useState({userId:row?.user_id??users[0]?.id??'',categoryId:row?.category_id??'',description:row?.description??'',priceType:row?.price_type??'FIXED',price:row?.price??'',priceUnit:row?.price_unit??'元/件',quantity:row?.quantity??'',quantityUnit:row?.quantity_unit??'pcs/cx',specText:row?.spec_text??'',regionCode:row?.region_code??'',status:row?.status??'PUBLISHED',imageUrl:row?.cover_url??''});
  const set=(k:string,v:any)=>setForm(s=>({...s,[k]:v}));
  async function submit(e:FormEvent){e.preventDefault();await api(`/api/v1/admin/products${row?`/${row.id}`:''}`,{method:row?'PUT':'POST',body:JSON.stringify({...form,userId:Number(form.userId),categoryId:form.categoryId?Number(form.categoryId):null,price:form.priceType==='NEGOTIABLE'?null:Number(form.price),quantity:form.quantity===''?null:Number(form.quantity)})});onSaved();}
  return <Modal title={row?'编辑商品':'新增商品'} onClose={onClose}><form onSubmit={submit} className="form-grid">
    <label className="wide">商品描述<textarea required minLength={2} value={form.description} onChange={e=>set('description',e.target.value)}/></label>
    <label>发布者<select required value={form.userId} onChange={e=>set('userId',e.target.value)}>{users.map(u=><option key={u.id} value={u.id}>{u.nickname}（#{u.id}）</option>)}</select></label>
    <label>分类<select value={form.categoryId} onChange={e=>set('categoryId',e.target.value)}><option value="">未分类</option>{categories.filter(c=>c.status==='ACTIVE').map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label>
    <label>价格类型<select value={form.priceType} onChange={e=>set('priceType',e.target.value)}><option value="FIXED">固定价格</option><option value="NEGOTIABLE">面议</option></select></label>
    <label>价格<input type="number" min="0" step="0.01" disabled={form.priceType==='NEGOTIABLE'} required={form.priceType==='FIXED'} value={form.price} onChange={e=>set('price',e.target.value)}/></label>
    <label>计价单位<input value={form.priceUnit} onChange={e=>set('priceUnit',e.target.value)}/></label><label>装箱数<input type="number" min="1" step="1" value={form.quantity} onChange={e=>set('quantity',e.target.value)}/></label>
    <label>装箱单位<input value={form.quantityUnit} placeholder="pcs/cx" onChange={e=>set('quantityUnit',e.target.value)}/></label><label>型号/规格<input value={form.specText} onChange={e=>set('specText',e.target.value)}/></label>
    <label>地区<input value={form.regionCode} onChange={e=>set('regionCode',e.target.value)}/></label><label>状态<select value={form.status} onChange={e=>set('status',e.target.value)}><option value="PUBLISHED">展示中</option><option value="OFF_SHELF">已下架</option><option value="SOLD">已售出</option><option value="VIOLATION">违规下架</option></select></label>
    <label className="wide">图片地址（选填）<input value={form.imageUrl} onChange={e=>set('imageUrl',e.target.value)} placeholder="http://localhost:3000/uploads/图片名.png"/></label>
    <div className="form-actions wide"><button type="button" onClick={onClose}>取消</button><button className="primary">保存</button></div>
  </form></Modal>;
}

function WantedForm({row,users,categories,onClose,onSaved}:{row?:Row;users:Row[];categories:Row[];onClose:()=>void;onSaved:()=>void}){
  const [f,setF]=useState({userId:row?.user_id??users[0]?.id??'',categoryId:row?.category_id??'',description:row?.description??'',targetPrice:row?.target_price??'',quantity:row?.quantity??'',specText:row?.spec_text??'',regionCode:row?.region_code??'',status:row?.status??'ACTIVE'});const set=(k:string,v:any)=>setF(s=>({...s,[k]:v}));
  async function submit(e:FormEvent){e.preventDefault();await api(`/api/v1/admin/wanted-posts${row?`/${row.id}`:''}`,{method:row?'PUT':'POST',body:JSON.stringify({...f,userId:Number(f.userId),categoryId:f.categoryId?Number(f.categoryId):null,targetPrice:f.targetPrice===''?null:Number(f.targetPrice)})});onSaved();}
  return <Modal title={row?'编辑找货需求':'新增找货需求'} onClose={onClose}><form onSubmit={submit} className="form-grid"><label className="wide">需求描述<textarea required value={f.description} onChange={e=>set('description',e.target.value)}/></label><label>发布者<select value={f.userId} onChange={e=>set('userId',e.target.value)}>{users.map(u=><option key={u.id} value={u.id}>{u.nickname}</option>)}</select></label><label>分类<select value={f.categoryId} onChange={e=>set('categoryId',e.target.value)}><option value="">未分类</option>{categories.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label><label>目标价格<input type="number" min="0" value={f.targetPrice} onChange={e=>set('targetPrice',e.target.value)}/></label><label>数量<input value={f.quantity} onChange={e=>set('quantity',e.target.value)}/></label><label>型号/规格<input value={f.specText} onChange={e=>set('specText',e.target.value)}/></label><label>地区<input value={f.regionCode} onChange={e=>set('regionCode',e.target.value)}/></label><label>状态<select value={f.status} onChange={e=>set('status',e.target.value)}>{['ACTIVE','FOUND','EXPIRED','OFF_SHELF','VIOLATION'].map(s=><option key={s} value={s}>{statusText[s]}</option>)}</select></label><div className="form-actions wide"><button type="button" onClick={onClose}>取消</button><button className="primary">保存</button></div></form></Modal>;
}

function UserForm({row,onClose,onSaved}:{row?:Row;onClose:()=>void;onSaved:()=>void}){
  const [f,setF]=useState({nickname:row?.nickname??'',regionCode:row?.region_code??'',status:row?.status??'ACTIVE',contactPolicy:row?.contact_policy??'LOGIN_ONLY'});const set=(k:string,v:any)=>setF(s=>({...s,[k]:v}));
  async function submit(e:FormEvent){e.preventDefault();await api(`/api/v1/admin/users${row?`/${row.id}`:''}`,{method:row?'PUT':'POST',body:JSON.stringify(f)});onSaved();}
  return <Modal title={row?'编辑用户':'新增测试用户'} onClose={onClose}><form onSubmit={submit} className="form-grid"><label>昵称<input required value={f.nickname} onChange={e=>set('nickname',e.target.value)}/></label><label>地区<input value={f.regionCode} onChange={e=>set('regionCode',e.target.value)}/></label><label>状态<select value={f.status} onChange={e=>set('status',e.target.value)}>{['ACTIVE','LIMITED','BANNED'].map(s=><option key={s} value={s}>{statusText[s]}</option>)}</select></label>{row&&<label>联系权限<select value={f.contactPolicy} onChange={e=>set('contactPolicy',e.target.value)}><option value="PUBLIC">公开</option><option value="LOGIN_ONLY">登录可见</option><option value="AFTER_INQUIRY">咨询后可见</option><option value="MEMBER_ONLY">会员可见</option></select></label>}<div className="form-actions wide"><button type="button" onClick={onClose}>取消</button><button className="primary">保存</button></div></form></Modal>;
}

function ReportForm({row,users,onClose,onSaved}:{row?:Row;users:Row[];onClose:()=>void;onSaved:()=>void}){
  const [f,setF]=useState({reporterUserId:row?.reporter_user_id??users[0]?.id??'',targetType:row?.target_type??'PRODUCT',targetId:row?.target_id??'',reasonCode:row?.reason_code??'OTHER',description:row?.description??'',status:row?.status??'OPEN',resolution:row?.resolution??''});
  const set=(k:string,v:any)=>setF(s=>({...s,[k]:v}));
  async function submit(e:FormEvent){e.preventDefault();await api(`/api/v1/admin/reports${row?`/${row.id}`:''}`,{method:row?'PUT':'POST',body:JSON.stringify({...f,reporterUserId:Number(f.reporterUserId),targetId:Number(f.targetId),resolution:f.resolution||null})});onSaved();}
  return <Modal title={row?'编辑举报':'新增举报'} onClose={onClose}><form onSubmit={submit} className="form-grid">
    <label>举报人<select required value={f.reporterUserId} onChange={e=>set('reporterUserId',e.target.value)}>{users.map(u=><option key={u.id} value={u.id}>{u.nickname}（#{u.id}）</option>)}</select></label>
    <label>举报对象<select value={f.targetType} onChange={e=>set('targetType',e.target.value)}><option value="PRODUCT">商品</option><option value="WANTED">找货需求</option><option value="USER">用户</option></select></label>
    <label>对象 ID<input required type="number" min="1" step="1" value={f.targetId} onChange={e=>set('targetId',e.target.value)}/></label>
    <label>举报原因<select value={f.reasonCode} onChange={e=>set('reasonCode',e.target.value)}>{['FAKE','SOLD_OUT','FAKE_PRICE','STOLEN_IMAGE','PROHIBITED','FRAUD','INVALID_CONTACT','SPAM','OTHER'].map(v=><option key={v} value={v}>{v}</option>)}</select></label>
    <label className="wide">补充说明<textarea maxLength={500} value={f.description} onChange={e=>set('description',e.target.value)}/></label>
    <label>处理状态<select value={f.status} onChange={e=>set('status',e.target.value)}>{['OPEN','PROCESSING','CLOSED'].map(v=><option key={v} value={v}>{statusText[v]}</option>)}</select></label>
    <label>处理结果<select value={f.resolution} onChange={e=>set('resolution',e.target.value)}><option value="">未填写</option>{['NO_VIOLATION','WARNED','CONTENT_REMOVED','USER_LIMITED','USER_BANNED'].map(v=><option key={v} value={v}>{v}</option>)}</select></label>
    <div className="form-actions wide"><button type="button" onClick={onClose}>取消</button><button className="primary">保存</button></div>
  </form></Modal>;
}

function CategoryForm({row,categories,onClose,onSaved}:{row?:Row;categories:Row[];onClose:()=>void;onSaved:()=>void}){const[f,setF]=useState({name:row?.name??'',parentId:row?.parent_id??'',level:row?.level??1,sortOrder:row?.sort_order??0,status:row?.status??'ACTIVE'});async function submit(e:FormEvent){e.preventDefault();await api(`/api/v1/admin/categories${row?`/${row.id}`:''}`,{method:row?'PUT':'POST',body:JSON.stringify({...f,parentId:f.parentId?Number(f.parentId):null})});onSaved();}return <Modal title={row?'编辑分类':'新增分类'} onClose={onClose}><form onSubmit={submit} className="form-grid"><label>分类名称<input required value={f.name} onChange={e=>setF({...f,name:e.target.value})}/></label><label>上级分类<select value={f.parentId} onChange={e=>setF({...f,parentId:e.target.value})}><option value="">无上级分类</option>{categories.filter(c=>c.id!==row?.id&&c.level<f.level).map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label><label>层级<select value={f.level} onChange={e=>setF({...f,level:Number(e.target.value),parentId:Number(e.target.value)===1?'':f.parentId})}><option value={1}>一级</option><option value={2}>二级</option><option value={3}>三级</option></select></label><label>排序<input type="number" value={f.sortOrder} onChange={e=>setF({...f,sortOrder:Number(e.target.value)})}/></label><label>状态<select value={f.status} onChange={e=>setF({...f,status:e.target.value})}><option value="ACTIVE">启用</option><option value="DISABLED">停用</option></select></label><div className="form-actions wide"><button type="button" onClick={onClose}>取消</button><button className="primary">保存</button></div></form></Modal>}

function RegionForm({row,onClose,onSaved}:{row?:Row;onClose:()=>void;onSaved:()=>void}){
  const [f,setF]=useState({code:row?.code??'',name:row?.name??'',sortOrder:row?.sort_order??100,status:row?.status??'ACTIVE'});
  async function submit(e:FormEvent){e.preventDefault();await api(`/api/v1/admin/regions${row?`/${row.code}`:''}`,{method:row?'PUT':'POST',body:JSON.stringify({...f,code:f.code.trim().toUpperCase().replace(/[^A-Z0-9]+/g,'_')})});onSaved();}
  return <Modal title={row?'编辑地区':'新增地区'} onClose={onClose}><form onSubmit={submit} className="form-grid">
    <label>地区编码<input required disabled={!!row} placeholder="例如：BRAS" value={f.code} onChange={e=>setF({...f,code:e.target.value})}/></label>
    <label>葡语地区名称<input required placeholder="例如：Brás" value={f.name} onChange={e=>setF({...f,name:e.target.value})}/></label>
    <label>排序<input type="number" min="0" step="1" value={f.sortOrder} onChange={e=>setF({...f,sortOrder:Number(e.target.value)})}/></label>
    <label>状态<select value={f.status} onChange={e=>setF({...f,status:e.target.value})}><option value="ACTIVE">启用</option><option value="DISABLED">停用</option></select></label>
    <div className="form-actions wide"><button type="button" onClick={onClose}>取消</button><button className="primary">保存</button></div>
  </form></Modal>;
}

function App(){
  const [page,setPage]=useState<Page>('dashboard'),[items,setItems]=useState<Row[]>([]),[users,setUsers]=useState<Row[]>([]),[categories,setCategories]=useState<Row[]>([]),[stats,setStats]=useState<Row>({}),[editing,setEditing]=useState<Row|undefined>(),[showForm,setShowForm]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState(''),[query,setQuery]=useState(''),[status,setStatus]=useState(''),[productPage,setProductPage]=useState(1),[productTotal,setProductTotal]=useState(0);
  const loadLookups=useCallback(async()=>{const[u,c]=await Promise.all([api('/api/v1/admin/users'),api('/api/v1/admin/categories')]);setUsers(u.items);setCategories(c.items)},[]);
  const load=useCallback(async(requestedProductPage=productPage)=>{try{setError('');setNotice('');const s=await api('/api/v1/admin/stats');setStats(s);await loadLookups();if(page==='dashboard'){setItems([]);return}const resource=page==='wanted'?'wanted-posts':page;const params=new URLSearchParams();if(query)params.set('q',query);if(status&&page!=='regions')params.set('status',status);if(page==='products'){params.set('page',String(requestedProductPage));params.set('pageSize','20')}const data=await api(`/api/v1/admin/${resource}?${params}`);setItems(data.items??[]);if(page==='products')setProductTotal(data.pagination?.total??0)}catch(e){setError(e instanceof Error?e.message:'加载失败')}},[page,query,status,productPage,loadLookups]);
  useEffect(()=>{setProductPage(1);load(1)},[page]);
  async function resetFilters(){setQuery('');setStatus('');setProductPage(1);try{const resource=page==='wanted'?'wanted-posts':page;const data=await api(`/api/v1/admin/${resource}${page==='products'?'?page=1&pageSize=20':''}`);setItems(data.items??[]);if(page==='products')setProductTotal(data.pagination?.total??0)}catch(e){setError(e instanceof Error?e.message:'重置失败')}}
  const productPages=Math.max(1,Math.ceil(productTotal/20));
  function goProductPage(nextPage:number){const safePage=Math.max(1,Math.min(productPages,nextPage));if(safePage===productPage)return;setProductPage(safePage);load(safePage)}
  async function remove(row:Row){if(!confirm(`确认删除/停用“${row.description??row.nickname??row.name??`#${row.id}`}”吗？`))return;try{const resource=page==='wanted'?'wanted-posts':page;const id=page==='regions'?row.code:row.id;await api(`/api/v1/admin/${resource}/${id}`,{method:'DELETE'});setNotice('操作成功，前台刷新后即可看到变化');load()}catch(e){setError(e instanceof Error?e.message:'操作失败')}}
  const saved=()=>{setShowForm(false);setEditing(undefined);setNotice('保存成功，数据已同步到前台');load()};
  function open(row?:Row){setEditing(row);setShowForm(true)}
  return <main><aside><div className="brand"><span>货</span><div>BuscaSP<small>本地运营中心</small></div></div><nav>{(Object.keys(labels) as Page[]).map(k=><button key={k} className={page===k?'active':''} onClick={()=>{setPage(k);setQuery('');setStatus('');setProductPage(1)}}><i>{({dashboard:'⌂',products:'▣',wanted:'⌕',users:'♙',reports:'!',categories:'≡',regions:'◎'} as any)[k]}</i>{labels[k]}</button>)}</nav><div className="local"><b>● 本地环境运行中</b><small>所有操作仅影响本机数据</small></div></aside>
  <section><header><div><h1>{labels[page]}</h1><p>{page==='dashboard'?'查看平台数据和本地运行情况':'在这里维护数据，操作结果会同步到小程序前台'}</p></div>{page!=='dashboard'&&<button className="primary" onClick={()=>open()}>＋ 新增{labels[page].replace('管理','').replace('配置','').replace('中心','')}</button>}</header>
  {error&&<div className="alert error">{error}</div>}{notice&&<div className="alert success">{notice}</div>}
  {page==='dashboard'?<><div className="stats">{[['用户总数',stats.users],['商品总数',stats.products],['展示中商品',stats.published_products],['有效找货',stats.active_wanted],['待处理举报',stats.open_reports],['联系次数',stats.contacts]].map(([l,v])=><article key={String(l)}><small>{l}</small><strong>{v??0}</strong></article>)}</div><div className="panel guide"><h2>本地运营流程</h2><div className="flow"><span>后台维护用户与分类</span><b>→</b><span>新增或编辑货源</span><b>→</b><span>小程序刷新查看</span><b>→</b><span>测试收藏、找货与联系</span></div></div></>:
  <div className="panel">{page!=='regions'&&<div className="toolbar"><input placeholder={{products:'搜索商品或发布者',wanted:'搜索需求或发布者',users:'搜索用户名称或 ID',reports:'搜索举报人、原因或说明',categories:'搜索分类名称',dashboard:''}[page]} value={query} onChange={e=>setQuery(e.target.value)} onKeyDown={e=>e.key==='Enter'&&load(page==='products'?1:productPage)}/>{page==='products'&&<select value={status} onChange={e=>setStatus(e.target.value)}><option value="">全部状态</option>{['PUBLISHED','OFF_SHELF','SOLD','VIOLATION'].map(s=><option key={s} value={s}>{statusText[s]}</option>)}</select>}{page==='wanted'&&<select value={status} onChange={e=>setStatus(e.target.value)}><option value="">全部状态</option>{['ACTIVE','FOUND','EXPIRED','OFF_SHELF','VIOLATION'].map(s=><option key={s} value={s}>{statusText[s]}</option>)}</select>}{page==='users'&&<select value={status} onChange={e=>setStatus(e.target.value)}><option value="">全部状态</option>{['ACTIVE','LIMITED','BANNED'].map(s=><option key={s} value={s}>{statusText[s]}</option>)}</select>}{page==='reports'&&<select value={status} onChange={e=>setStatus(e.target.value)}><option value="">全部状态</option>{['OPEN','PROCESSING','CLOSED'].map(s=><option key={s} value={s}>{statusText[s]}</option>)}</select>}{page==='categories'&&<select value={status} onChange={e=>setStatus(e.target.value)}><option value="">全部状态</option>{['ACTIVE','DISABLED'].map(s=><option key={s} value={s}>{statusText[s]}</option>)}</select>}<button className="primary" onClick={()=>{if(page==='products')setProductPage(1);load(page==='products'?1:productPage)}}>查询</button><button onClick={resetFilters}>重置</button></div>}{page==='regions'&&<div className="toolbar"><input placeholder="搜索地区编码或名称" value={query} onChange={e=>setQuery(e.target.value)}/><button className="primary" onClick={()=>load()}>查询</button></div>}
  <div className="table-wrap"><table><thead><tr>{page==='products'&&<><th>商品</th><th>价格</th><th>发布者</th><th>分类/地区</th><th>状态</th><th>操作</th></>}{page==='wanted'&&<><th>需求</th><th>发布者</th><th>目标价格</th><th>回应</th><th>状态</th><th>操作</th></>}{page==='users'&&<><th>用户</th><th>地区</th><th>货源</th><th>找货</th><th>状态</th><th>操作</th></>}{page==='reports'&&<><th>举报人</th><th>对象</th><th>原因</th><th>时间</th><th>状态</th><th>操作</th></>}{page==='categories'&&<><th>分类</th><th>层级</th><th>排序</th><th>状态</th><th>操作</th></>}</tr></thead><tbody>
  {items.map(r=><tr key={r.id}>{page==='products'&&<><td><div className="product-cell">{r.cover_url?<img src={r.cover_url}/>:<span className="thumb">无图</span>}<div><b>#{r.id}</b> {r.description}<small>{r.spec_text||'未填写规格'}</small></div></div></td><td>{r.price_type==='NEGOTIABLE'?'面议':`¥${r.price} ${r.price_unit??''}`}</td><td>{r.nickname}</td><td>{r.category_name??'未分类'}<small>{r.region_code??'未填写地区'}</small></td><td>{badge(r.status)}</td><td><button className="link" onClick={()=>open(r)}>编辑</button><button className="link danger" onClick={()=>remove(r)}>删除</button></td></>}
  {page==='wanted'&&<><td><b>#{r.id}</b> {r.description}<small>{r.spec_text||'未填写规格'}</small></td><td>{r.nickname}</td><td>{r.target_price?`¥${r.target_price}`:'未填写'}</td><td>{r.response_count}</td><td>{badge(r.status)}</td><td><button className="link" onClick={()=>open(r)}>编辑</button><button className="link danger" onClick={()=>remove(r)}>删除</button></td></>}
  {page==='users'&&<><td><b>{r.nickname}</b><small>用户 #{r.id} · {r.login_source==='WECHAT'?'微信登录':'本地测试'}</small></td><td>{r.region_code??'未填写'}<small>最后登录：{fmt(r.last_login_at)}</small></td><td>{r.product_count}</td><td>{r.wanted_count}</td><td>{badge(r.status)}</td><td><button className="link" onClick={()=>open(r)}>编辑</button><button className="link danger" onClick={()=>remove(r)}>删除</button></td></>}
  {page==='reports'&&<><td>{r.reporter_name}</td><td>{r.target_type} #{r.target_id}</td><td>{r.reason_code}<small>{r.description}</small></td><td>{fmt(r.created_at)}</td><td>{badge(r.status)}</td><td><button className="link" onClick={()=>open(r)}>编辑</button><button className="link danger" onClick={()=>remove(r)}>删除</button></td></>}
  {page==='categories'&&<><td><b>{r.name}</b><small>分类 #{r.id}{r.parent_name?` · 上级：${r.parent_name}`:''}</small></td><td>{r.level} 级</td><td>{r.sort_order}</td><td>{badge(r.status)}</td><td><button className="link" onClick={()=>open(r)}>编辑</button><button className="link danger" onClick={()=>remove(r)}>停用</button></td></>}</tr>)}
  {!items.length&&<tr><td colSpan={8} className="empty">暂无数据，可以点击右上角新增。</td></tr>}</tbody></table></div>{page==='products'&&<div className="pagination"><span>共 {productTotal} 件商品 · 第 {productPage} / {productPages} 页</span><div><button disabled={productPage<=1} onClick={()=>goProductPage(productPage-1)}>上一页</button><button disabled={productPage>=productPages} onClick={()=>goProductPage(productPage+1)}>下一页</button></div></div>}</div>}
  </section>
  {showForm&&page==='products'&&<ProductForm row={editing} users={users} categories={categories} onClose={()=>setShowForm(false)} onSaved={saved}/>} {showForm&&page==='wanted'&&<WantedForm row={editing} users={users} categories={categories} onClose={()=>setShowForm(false)} onSaved={saved}/>} {showForm&&page==='users'&&<UserForm row={editing} onClose={()=>setShowForm(false)} onSaved={saved}/>} {showForm&&page==='reports'&&<ReportForm row={editing} users={users} onClose={()=>setShowForm(false)} onSaved={saved}/>} {showForm&&page==='categories'&&<CategoryForm row={editing} categories={categories} onClose={()=>setShowForm(false)} onSaved={saved}/>} {showForm&&page==='regions'&&<RegionForm row={editing} onClose={()=>setShowForm(false)} onSaved={saved}/>}</main>;
}
createRoot(document.getElementById('root')!).render(<App/>);
