ALTER TABLE users ADD COLUMN IF NOT EXISTS unionid VARCHAR(64);
ALTER TABLE users ADD COLUMN IF NOT EXISTS login_source VARCHAR(20) NOT NULL DEFAULT 'DEV';
ALTER TABLE users ADD COLUMN IF NOT EXISTS last_login_at TIMESTAMPTZ;
CREATE UNIQUE INDEX IF NOT EXISTS users_unionid_unique ON users(unionid) WHERE unionid IS NOT NULL;

